### PR TITLE
Support update product stock

### PR DESCRIPTION
**Pull request by huynv-0947**
==> Title: Support update product stock

==> Redmine: https://edu-redmine.sun-asterisk.vn/issues/18604

==> Attachment File:

SUPPORT_UPDATE_PRODUCT_STOCK

### CODE REVIEW

**Comment by huynv-0947** [comment]
ready

**Comment by phucmh-1356** [comment]
commented
2 commits

**Comment by huynv-0947** [comment]
ready

**Comment by phucmh-1356** [comment]
commented
conflict

**Pull request closed without merging**
